bugcrowd/vulnerability-rating-taxonomy

- README.md
We've moved to use "N/A" instead of "Varies" to be more informative about what that actually means.
> N/A -> Varies

- CHANGELOG.md
- CONTRIBUTING.md
- validate-vrt.py
- vulnerability-rating-taxonomy.json
I am not a huge fan of the add/remove entries for a node that is being moved and keeping the subcategory/variants but unsure how else to do it. I tried doing it within `Changed`: 
```
- mobile_security_misconfiguration.ssl_certificate_pinning change category from insecure_data_transport to mobile_security_misconfiguration
```
but that seems a bit awkward as well. Open to other ideas?
> Changelog entry per merge

- CHANGELOG.md
- CONTRIBUTING.md
- README.md
- deprecated-node-mapping.json
- validate-deprecated-mapping.py
- vulnerability-rating-taxonomy.json
closes this issue: https://github.com/bugcrowd/vulnerability-rating-taxonomy/issues/24
> Add deprecated node mapping and info/example to readme

- CHANGELOG.md
- deprecated-node-mapping.json
- vulnerability-rating-taxonomy.json
As discussed internally today this resolves #38. We are removing the entire `Broken Authentication and Session Management->Session Token in URL` subcategory and leaving `Sensitive Data Exposure->Sensitive Token in URL (P4)`. We will no longer distinguish session from sensitive tokens in URL nor will we differentiate HTTP from HTTPS in this particular case.
I am also moving the existing `Sensitive Data Exposure->Non-Sensitive Token in URL (P5)` directly below its sensitive counterpart.
> Fix Sensitive/Session Token in URL

- CHANGELOG.md
- vulnerability-rating-taxonomy.json
This resolves #22. As discussed internally we are addressing JSON Hijacking as a separate P5 entry due to a very low probability of exploitation on modern browsers. Classifying this type of issues as P5 provides multiple benefits to a crowd sourced taxonomy. As a general rule priority can be upgraded on a case by case basis leaving the door open for valid findings.
> Add JSON Hijacking

- CHANGELOG.md
- vulnerability-rating-taxonomy.json
Minor spelling mistake. Does not affect the node `id` so it should be backwards-compatible.
> Applicaton -> application

- CHANGELOG.md
- deprecated-node-mapping.json
`insufficient_security_configurability.weak_password_policy.no_password_policy` doesn't actually exist in `1.2`, it was added as `insufficient_security_configurability.no_password_policy` (see #66). But the references in the deprecated node mapping and changelog used the wrong id. So:
1. How do we document this in the changelog? It's kinda a weird case, but I had a go. Open to suggestions.
2. Do we want to update the old info in the changelog? We possibly should because the old changelog entry doesn't correctly reflect what happened but on the other hand, editing info for old releases does seem kinda bad.
3. Was `no_password_policy` actually intended to be added as a child of `weak_password_policy`? I have no opinions on this I just want to check whether the mistake was in the …
> Fix invalid id in deprecated node mapping

- CHANGELOG.md
We should keep our master changelog up to date, even though none of the commits for v1.3.1 are on this branch (they're all on [1.3-stable](https://github.com/bugcrowd/vulnerability-rating-taxonomy/tree/1.3-stable)). This duplicates the changelog entry for the backported fix between the unreleased and v1.3.1 sections but that is actually an accurate reflection of how it happened in the git tree so maybe it's okay. We can also remove that entry from Unreleased if people have strong opinions.
> Add changelog entry for v1.3.1

- CHANGELOG.md
- vulnerability-rating-taxonomy.json
As discussed internally we are updating the variant `Broken Authentication and Session Management->Failure to Invalidate Session->All Sessions` to `Broken Authentication and Session Management->Failure to Invalidate Session->Concurrent Sessions On Logout` to ensure clarity.
**Issue**: N/A
**[CVSS v3 Mapping](https://github.com/bugcrowd/vulnerability-rating-taxonomy/blob/master/mappings/cvss_v3.json)**: N/A
**[Deprecated Node Mapping](https://github.com/bugcrowd/vulnerability-rating-taxonomy/blob/master/deprecated-node-mapping.json)** (_if needed_): N/A
> Update 'All Sessions' to 'Concurrent Sessions On Logout'

- .github/CONTRIBUTING.md
Since labeling can only be done by contributors, we should not be asking new contributors to set them.
This was brought up by @edoverflow in #111.
> remove mention of labeling within CONTRIBUTING.md

- mappings/cwe.json
This is a general update of CWE mappings for #112. The default CWE mapping has been set to CWE-2000, this means that any top category that doesn't have a representation in CWE will have this mapping assigned (this also includes the "Other" category). Perhaps there's a more suitable choice...
Any feedback from the community is as always welcome and appreciated. Please note that our mapping logic allows all VRT child nodes to inherit their parent mappings in case a mapping for a specific child node is not explicitly defined. This makes for a concise mapping file structure.
> Update all VRT to CWE mappings

- CHANGELOG.md
- vulnerability-rating-taxonomy.json
**Issue**: Resolves #127 
As discussed in the issue ^ it was decided to downgrade `Server Security Misconfiguration > No Rate Limiting on Form > Login` to P4. At the same time it's worth noting that if this entry is chained with Insufficient Security Configurability > No Password Policy, that would result in a P3 rating
> Downgrade No Rate Limiting on Login to P4

- README.md
Vulnerability Roundtable has been divided into two separate meetings: Vulnerability Roundtable and VRT Council. VRT Council will be focusing on VRT related issues specifically and the proposed readme changes reflect that.
> Update readme with VRT Council

- Dockerfile
- tests/test_deprecated_mapping.py
When removing ids, it makes sense to add the entries to the deprecated node mapping before the next release is made. In that case, we should check the id is valid based on the current branch, rather than erroring out with an unknown version.
Fixes the build errors in https://github.com/bugcrowd/vulnerability-rating-taxonomy/pull/138
```
git checkout downgrade-weak-p4s
docker build -t vrt .
docker run -v $(pwd):/tmp/vrt vrt # should fail
git merge --no-commit fix-deprecated-node-test
docker build -t vrt .
docker run -v $(pwd):/tmp/vrt vrt # should pass
```
> Allow versions greater than the last tag in the deprecated node mapping

- CHANGELOG.md
- deprecated-node-mapping.json
- mappings/cvss_v3.json
- vulnerability-rating-taxonomy.json
**Issue**: Resolves #133 
**[Deprecated Node Mapping](https://github.com/bugcrowd/vulnerability-rating-taxonomy/blob/master/deprecated-node-mapping.json)**:
- `cross_site_scripting_xss.ie_only.older_version_ie_10_11` to `cross_site_scripting_xss.ie_only.ie11`
- `cross_site_scripting_xss.ie_only.older_version_ie10`to  `cross_site_scripting_xss.ie_only.older_version_ie11`
- `broken_authentication_and_session_management.failure_to_invalidate_session.on_password_reset` to `broken_authentication_and_session_management.failure_to_invalidate_session.on_password_change`
Let's triple check that these changes make sense
P.S. Looks like there might be some test problems due to 1.3.1 version interfering with 1.4
> Downgrade weak P4's

- CHANGELOG.md
- deprecated-node-mapping.json
- mappings/cvss_v3.json
- vulnerability-rating-taxonomy.json
**Issue**: Resolves #140 
**[CVSS v3 Mapping](https://github.com/bugcrowd/vulnerability-rating-taxonomy/blob/master/mappings/cvss_v3.json)**: `network_security_misconfiguration.telnet_enabled` [AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N](https://www.first.org/cvss/calculator/3.0#CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N)
**[Deprecated Node Mapping](https://github.com/bugcrowd/vulnerability-rating-taxonomy/blob/master/deprecated-node-mapping.json)**: `network_security_misconfiguration.telnet_enabled.credentials_required` to `broken_authentication_and_session_management.weak_login_function.other_plaintext_protocol_no_secure_alternative`
> Remove 'Network Security Misconfiguration > Telnet Enabled > Credentials Required'

- CHANGELOG.md
- mappings/cvss_v3.json
- mappings/remediation_advice.json
- vulnerability-rating-taxonomy.json
**Issue**: Resolves #120
`cross_site_scripting_xss.flash_based` [AV:N/AC:H/PR:N/UI:R/S:C/C:L/I:L/A:N](https://www.first.org/cvss/calculator/3.0#CVSS:3.0/AV:N/AC:H/PR:N/UI:R/S:C/C:L/I:L/A:N)
`server_side_injection.content_spoofing.flash_based_external_authentication_injection` [AV:N/AC:H/PR:N/UI:R/S:U/C:N/I:L/A:N](https://www.first.org/cvss/calculator/3.0#CVSS:3.0/AV:N/AC:H/PR:N/UI:R/S:U/C:N/I:L/A:N)
`unvalidated_redirects_and_forwards.open_redirect.flash_based` default as the category
**[Remediation Advice Mapping](https://github.com/bugcrowd/vulnerability-rating-taxonomy/blob/master/mappings/remediation_advice.json)**: Reused …
> Add Flash-Based variants

- CHANGELOG.md
- mappings/remediation_advice.json
- vulnerability-rating-taxonomy.json
**Issue**: Resolves #169 
**[CVSS v3 Mapping](https://github.com/bugcrowd/vulnerability-rating-taxonomy/blob/master/mappings/cvss_v3.json)**: Inherited from the parent [AV:N/AC:L/PR:N/UI:N/S:C/C:N/I:L/A:N](https://www.first.org/cvss/calculator/3.0#CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:C/C:N/I:L/A:N)
**[CWE Mapping](https://github.com/bugcrowd/vulnerability-rating-taxonomy/blob/master/mappings/cwe.json)**: Inherited from the parent [CWE-799](https://cwe.mitre.org/data/definitions/799.html)
```
1. Use a `CAPTCHA` to limit SMS triggering requests.
2. Use a rate limit per IP address to throttle the amount of SMS triggering requests that can be made in a certain …
```
> Add no rate limit on SMS triggering

- CHANGELOG.md
- deprecated-node-mapping.json
- mappings/cvss_v3.json
- mappings/remediation_advice.json
- vulnerability-rating-taxonomy.json
**Issue**: Resolves #167 
**[CVSS v3 Mapping](https://github.com/bugcrowd/vulnerability-rating-taxonomy/blob/master/mappings/cvss_v3.json)**: No change - [AV:N/AC:L/PR:N/UI:R/S:U/C:L/I:L/A:N](https://www.first.org/cvss/calculator/3.0#CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:U/C:L/I:L/A:N)
**[CWE Mapping](https://github.com/bugcrowd/vulnerability-rating-taxonomy/blob/master/mappings/cwe.json)**: No change - none
**[Remediation Advice Mapping](https://github.com/bugcrowd/vulnerability-rating-taxonomy/blob/master/mappings/remediation_advice.json)**: Merged -
"1. Create a `Sender Policy Framework` record for the domain in which your emails originate. This will help prevent attackers from sending spoof emails that may look like they originate from your domain. The SPF record will be configurable by your …
> Revise email spoofing variants

- CHANGELOG.md
- deprecated-node-mapping.json
- mappings/cvss_v3.json
- vulnerability-rating-taxonomy.json
**Issue**: Resolves #166 
`privileged_user_to_privilege_elevation`: [AV:N/AC:L/PR:H/UI:N/S:C/C:H/I:H/A:N](https://www.first.org/cvss/calculator/3.0#CVSS:3.0/AV:N/AC:L/PR:H/UI:N/S:C/C:H/I:H/A:N)
`privileged_user_to_no_privilege_elevation`: [AV:N/AC:L/PR:H/UI:N/S:C/C:L/I:L/A:N](https://www.first.org/cvss/calculator/3.0#CVSS:3.0/AV:N/AC:L/PR:H/UI:N/S:C/C:L/I:L/A:N)
**[CWE Mapping](https://github.com/bugcrowd/vulnerability-rating-taxonomy/blob/master/mappings/cwe.json)**: N/A (inherited from the parent)
**[Remediation Advice Mapping](https://github.com/bugcrowd/vulnerability-rating-taxonomy/blob/master/mappings/remediation_advice.json)**: N/A (inherited from the parent) …
> Revise Stored XSS > Admin to Anyone

- CHANGELOG.md
- mappings/cvss_v3.json
- mappings/remediation_advice.json
- vulnerability-rating-taxonomy.json
**Issue**: Resolves #179 
**[CVSS v3 Mapping](https://github.com/bugcrowd/vulnerability-rating-taxonomy/blob/master/mappings/cvss_v3.json)**: [AV:N/AC:H/PR:N/UI:R/S:U/C:N/I:L/A:N](https://www.first.org/cvss/calculator/3.0#CVSS:3.0/AV:N/AC:H/PR:N/UI:R/S:U/C:N/I:L/A:N)
**[CWE Mapping](https://github.com/bugcrowd/vulnerability-rating-taxonomy/blob/master/mappings/cwe.json)**: Inherited from parent [CWE-451](https://cwe.mitre.org/data/definitions/451.html)
"1. Use the `X-Frame-Options: DENY` HTTP response header on pages with sensitive information, to disallow framing of the page on external resources.
2. In the case where `DENY` is not an option, use …
> Revise Clickjacking

- CHANGELOG.md
- deprecated-node-mapping.json
- mappings/cvss_v3.json
- mappings/remediation_advice.json
- vulnerability-rating-taxonomy.json
**Issue**: Resolves #183 
-`basic_subdomain_takeover`: [AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:N](https://www.first.org/cvss/calculator/3.0#CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:N)
-`high_impact_subdomain_takeover`: [AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:H/A:N](https://www.first.org/cvss/calculator/3.0#CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:H/A:N)
**[CWE Mapping](https://github.com/bugcrowd/vulnerability-rating-taxonomy/blob/master/mappings/cwe.json)**: Inherited from parent `server_security_misconfiguration` [CWE-16](https://cwe.mitre.org/data/definitions/16.html)
**[Remediation Advice Mapping](https://github.com/bugcrowd/vulnerability-rating-taxonomy/blob/master/mappings/remediatio …
> Revise Subdomain Takeover

- CHANGELOG.md
- mappings/cvss_v3.json
- mappings/remediation_advice.json
- vulnerability-rating-taxonomy.json
**Issue**: Resolves #199 
**[CVSS v3 Mapping](https://github.com/bugcrowd/vulnerability-rating-taxonomy/blob/master/mappings/cvss_v3.json)**: [AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:L](https://www.first.org/cvss/calculator/3.0#CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:L)
**[CWE Mapping](https://github.com/bugcrowd/vulnerability-rating-taxonomy/blob/master/mappings/cwe.json)**: Inherited from parent [CWE-640](https://cwe.mitre.org/data/definitions/640.html)
"If the web application makes use of the host header value when composing the reset link, an attacker can poison the password reset link that is sent to a victim. If the victim clicks on the poisoned …
> Add Password Reset Token Leakage via Host Header Poisoning on Password Reset Function

- CHANGELOG.md
- mappings/remediation_advice.json
- vulnerability-rating-taxonomy.json
**Issue**: Resolves #204
**[CVSS v3 Mapping](https://github.com/bugcrowd/vulnerability-rating-taxonomy/blob/master/mappings/cvss_v3.json)**: Inherited from parent [AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N](https://www.first.org/cvss/calculator/3.0#CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N)
**[CWE Mapping](https://github.com/bugcrowd/vulnerability-rating-taxonomy/blob/master/mappings/cwe.json)**: Inherited from parent [CWE-16](https://cwe.mitre.org/data/definitions/16.html)
"Consider adding email spoofing protections for all your domains as attackers may resort to spoofing those, regardless of whether emails originate from them or not. Victims can still be …
> Add email spoofing on non-email domain

- CHANGELOG.md
- mappings/cvss_v3.json
- mappings/remediation_advice.json
- vulnerability-rating-taxonomy.json
**Issue**: Resolves #203 
**[CVSS v3 Mapping](https://github.com/bugcrowd/vulnerability-rating-taxonomy/blob/master/mappings/cvss_v3.json)**: [AV:P/AC:H/PR:N/UI:N/S:U/C:L/I:L/A:N](https://www.first.org/cvss/calculator/3.0#CVSS:3.0/AV:P/AC:H/PR:N/UI:N/S:U/C:L/I:L/A:N)
**[CWE Mapping](https://github.com/bugcrowd/vulnerability-rating-taxonomy/blob/master/mappings/cwe.json)**: N/A (inherited from the category)
"Ensure that the second factor authentication is properly configured and cannot be bypassed. 2FA secret should be rotated every time 2FA is reenabled by the user and not remain obtainable after 2FA is turned on. Additionally consider providing a 2FA …
> Add 2FA secret related entries

- CHANGELOG.md
- deprecated-node-mapping.json
- mappings/cvss_v3.json
- mappings/cvss_v3.schema.json
- mappings/cwe.schema.json
- mappings/remediation_advice.json
- mappings/remediation_advice.schema.json
- vrt.schema.json
- vulnerability-rating-taxonomy.json
**Issue**: Resolves #216
Only allowing numbers in the front of an id means that some things end up being represented as both a number and the spelled out version.  Operations team has decided to go with enforcing a more strict json schema to enforce uniformity.
This will avoid strange situations like this:
**[CVSS v3 Mapping](https://github.com/bugcrowd/vulnerability-rating-taxonomy/blob/master/mappings/cvss_v3.json)**: no change
**[CWE Mapping](https://github.com/bugcrowd/vulnerability-rating-taxonomy/blob/master/mappings/cwe.json)**: no change
**[Remediation Advice Mapping](https://github.com/bugcrowd/vulnerability-rating-taxonomy/blob/master/mappings/remediation_advice.json)**: no change
**[Deprecated Node Mapping](https://github.com/bugcrowd/vulnerability-rating-taxonomy/blob/master/de …
> Enforce uniformity in id's by disallowing numbers

- Dockerfile
Attempt to prevent buildkite failures by not writing pyc files that do not get deleted
Currently most of our builds in buildkite fail because the initial step of cloning the repository fails because the working directory is not empty.
The working directory fails to be emptied because the contents is owned by root so the buildkite agent user is unable to delete the files within.
After some investigation with @tessereth , the only files that are there are the generated .pyc files.  Setting this ENV var should prohibit docker from generating these files when running the tests.
python docs: https://docs.python.org/3/using/cmdline.html#envvar-PYTHONDONTWRITEBYTECODE
> fix buildkite builds

- CHANGELOG.md
- mappings/remediation_advice/remediation_advice.json
- vulnerability-rating-taxonomy.json
**Issue**: Resolves #217 
**[CVSS v3 Mapping](https://github.com/bugcrowd/vulnerability-rating-taxonomy/blob/master/mappings/cvss_v3.json)**: Inherited from parent [AV:N/AC:H/PR:N/UI:R/S:U/C:N/I:N/A:N](https://www.first.org/cvss/calculator/3.0#CVSS:3.0/AV:N/AC:H/PR:N/UI:R/S:U/C:N/I:N/A:N)
**[CWE Mapping](https://github.com/bugcrowd/vulnerability-rating-taxonomy/blob/master/mappings/cwe.json)**: Inherited from parent [CWE-929](https://cwe.mitre.org/data/definitions/929.html)
"Always ensure that email contents cannot be tampered with. Limit what the user can insert into the email by filtering special characters and limiting the amount of characters that …
> add Email Hyperlink Injection

- CHANGELOG.md
- mappings/cvss_v3/cvss_v3.json
- mappings/cwe/cwe.json
- mappings/remediation_advice/remediation_advice.json
- vulnerability-rating-taxonomy.json
Reverts bugcrowd/vulnerability-rating-taxonomy#239
We need to add the automotive mappings first to release as a patch.
> Revert "Add Indicators of Compromise category"

- CHANGELOG.md
- README.md
- mappings/cvss_v3/cvss_v3.json
- mappings/remediation_advice/remediation_advice.json
The purpose of this PR is to add mappings (remediation advice and CVSS) for the new Automotive Security Misconfiguration category. All feedback is welcome!
Currently rf_hub.unauthorized_access_turn_on remediation advice is missing as well as the entire CVSS mapping
> Add Automotive Security Misconfiguration mappings

- CHANGELOG.md
- mappings/cvss_v3/cvss_v3.json
- mappings/remediation_advice/remediation_advice.json
- vulnerability-rating-taxonomy.json
> Add Failure to Invalidate Session on 2FA Activation/Change

- CHANGELOG.md
- vulnerability-rating-taxonomy.json
> v1.8 release

- CHANGELOG.md
- mappings/cvss_v3/cvss_v3.json
- mappings/cwe/cwe.json
- mappings/remediation_advice/remediation_advice.json
- vulnerability-rating-taxonomy.json
- sensitive_data_exposure.via_localstorage_sessionstorage.sensitive_token: [AV:N/AC:H/PR:N/UI:N/S:U/C:L/I:N/A:N](https://www.first.org/cvss/calculator/3.0#CVSS:3.0/AV:N/AC:H/PR:N/UI:N/S:U/C:L/I:N/A:N)
- sensitive_data_exposure.via_localstorage_sessionstorage.non_sensitive_token: [AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:N](https://www.first.org/cvss/calculator/3.0#CVSS:3.0/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:N)
[CWE-922: Insecure Storage of Sensitive Information](https://cwe.mitre.org/data/definitions/922.html)
"Do not store anything sensitive in localStorage and any critical data in sessionStorage. Stick with properly secured cookies utilizing HTTPOnly and Secure flags"
references:
http://michael-coates.blogspot.com/2010/07/html5-local-storage-and-xss.html
> Add Sensitive Data Exposure in local/sessionStorage

- CHANGELOG.md
- mappings/cvss_v3/cvss_v3.json
- mappings/cwe/cwe.json
- mappings/remediation_advice/remediation_advice.json
- vulnerability-rating-taxonomy.json
server_side_injection.content_spoofing.impersonation_via_broken_link_hijacking: [AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:L/A:N](https://www.first.org/cvss/calculator/3.0#CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:L/A:N)
Updated parent node - server_side_injection.content_spoofing: [CWE-451](https://cwe.mitre.org/data/definitions/451.html)
In order to prevent this type of injection consider the following solutions:
1. Keep track of company's public 3rd party accounts, that includes social media. Whenever one is deleted, make sure it is not referenced in the application
2. Monitor all hyperlinks pointing to 3rd party resources, as well as any other external references for that matter, and make sure that they do not become invalid, e.g. check for change in HTTP response code. In many cases it may be …
> Add Broken Link Hijacking

- CHANGELOG.md
- mappings/cvss_v3/cvss_v3.json
- mappings/remediation_advice/remediation_advice.json
- vulnerability-rating-taxonomy.json
1. Use a `CAPTCHA` to limit current password check requests sent when changing account password.
2. Use a rate limit per IP address to throttle the amount of said requests that can be made in a certain amount of time.
> Add lack of rate limiting on current password when changing password

- CHANGELOG.md
- mappings/cvss_v3/cvss_v3.json
- mappings/remediation_advice/remediation_advice.json
- vulnerability-rating-taxonomy.json
Consider disabling auto backup of any sensitive application data. In Android you can disable auto backup by setting `android:allowBackup` in your app manifest file to false.
https://developer.android.com/guide/topics/data/autobackup
> Add Auto Backup Allowed by Default

- CHANGELOG.md
- mappings/cvss_v3/cvss_v3.json
- vulnerability-rating-taxonomy.json
- High Impact Flash-based CSRF: [AV:N/AC:H/PR:N/UI:R/S:U/C:L/I:H/A:N](https://www.first.org/cvss/calculator/3.0#CVSS:3.0/AV:N/AC:H/PR:N/UI:R/S:U/C:L/I:H/A:N)
- Low Impact Flash-based CSRF: [AV:N/AC:H/PR:N/UI:R/S:U/C:N/I:L/A:N](https://www.first.org/cvss/calculator/3.0#CVSS:3.0/AV:N/AC:H/PR:N/UI:R/S:U/C:N/I:L/A:N)
> Add Flash Based CSRF

- CHANGELOG.md
- mappings/remediation_advice/remediation_advice.json
- vulnerability-rating-taxonomy.json
"Ensure that the second factor authentication is properly configured, has sufficient rate limiting, and cannot be bypassed. 2FA secret should be rotated every time 2FA is reenabled by the user and not remain obtainable after 2FA is turned on. Additionally consider providing a 2FA failsafe mechanism so the users can safely recover their accounts."
> Add 2FA Code Invalidation Cases

- CHANGELOG.md
- mappings/cvss_v3/cvss_v3.json
- mappings/remediation_advice/remediation_advice.json
- vulnerability-rating-taxonomy.json
"In case of OAuth based account registration, ensure that if there is a preexisting account for the same email address and is to be merged, that it will no longer be accessible with its old password"
> Add OAuth Account Squatting

- README.md
* Fixes Build badge, pointing to GitHub Actions since we moved from Buildkite.
* Adjusts API for VRT link so it properly resolves.
> Fix Broken links/images in Readme

- mappings/cvss_v3/cvss_v3.json
- mappings/cwe/cwe.json
- mappings/remediation_advice/remediation_advice.json
- vulnerability-rating-taxonomy.json
> json formatting and parsing error fix

- deprecated-node-mapping.json
> deprecated-node-json-fix

- CHANGELOG.md
- mappings/cvss_v3/cvss_v3.json
- mappings/cwe/cwe.json
- mappings/remediation_advice/remediation_advice.json
- vulnerability-rating-taxonomy.json
Adding:
Application Level DoS - Excessive Resource Consumption - Injection (Prompt) - Varies
AI Application Security - Large Language Model (LLM) Security - Prompt Injection - P1
AI Application Security - Large Language Model (LLM) Security - LLM Output Handling - P1
AI Application Security - Large Language Model (LLM) Security - Training Data Poisoning - P1
AI Application Security - Large Language Model (LLM) Security - Excessive Agency/Permission Manipulation - P2
> AI Application Security(LLM)
