vulnerability-rating-taxonomy.json

Implementing #4,#5 and #6 for clarity and to avoid merging conflicts since they all address the same subcategory

Revise 'Visible Detailed Error Page' Subcategory

---

vulnerability-rating-taxonomy.json

Add Missing DKIM Classification

---

vulnerability-rating-taxonomy.json

Remove 'Insecure Data Transport’ Category

---

vulnerability-rating-taxonomy.json

Consolidated GET-based Open Redirect

---

vulnerability-rating-taxonomy.json

Add Internal IP and Path Disclosure

---

vulnerability-rating-taxonomy.json

Add Cookie Scoped to Parent Domain

---

vulnerability-rating-taxonomy.json

Add Binary Planting

---

CHANGELOG.md

Fixing the changelog entry order to chronological (newest at the bottom)

Fix Changelog Ordering

---

CHANGELOG.md
vulnerability-rating-taxonomy.json

As discussed during the vulnerability roundtable this resolves #20

Fix 'Token Leakage via Referer'

---

CHANGELOG.md
vulnerability-rating-taxonomy.json

As discussed during the vulnerability roundtable this resolves #26. @barnett you might be interested in looking at the changelog to make sure it's fine.

Fix 'Mixed Content' Subcategory

---

CHANGELOG.md
vulnerability-rating-taxonomy.json

Add Fingerprinting/Banner Disclosure

---

CHANGELOG.md
vulnerability-rating-taxonomy.json

Add Lack of Password Confirmation when Managing 2FA

---

CHANGELOG.md
vulnerability-rating-taxonomy.json

Add Logout CSRF

---

CHANGELOG.md
vulnerability-rating-taxonomy.json

Revise 'Authentication Bypass' Subcategory

---

CHANGELOG.md
vulnerability-rating-taxonomy.json

Add DNS Zone Transfer

---

README.md

Am down to consider other locations for this info.

Add vrt-ruby repo to supported libraries section

---

CHANGELOG.md
deprecated-node-mapping.json
vulnerability-rating-taxonomy.json

Revise 'Weak Password Policy' Subcategory

---

CHANGELOG.md
vulnerability-rating-taxonomy.json

Add Server-Side Plaintext Credentials Storage

---

CHANGELOG.md
vulnerability-rating-taxonomy.json

Add Cleartext Transmission of Sensitive Data

---

README.md

Thanks @adamrdavid for the design from https://github.com/bugcrowd/vrt-ruby

Add image and buildkite badge to Readme

---

CHANGELOG.md
deprecated-node-mapping.json
vulnerability-rating-taxonomy.json

Add Broken Access Control

---

CHANGELOG.md
vulnerability-rating-taxonomy.json

Add Tapjacking Classification

---

CHANGELOG.md
vulnerability-rating-taxonomy.json

Add Missing DNS CAA Record

---

CONTRIBUTING.md
README.md

Updating Readme with Vulnerability Roundtable minutes and clarifying priority rating process plus some broken URL fixes

Update Readme and fix broken URLs

---

CHANGELOG.md
mappings/cvss_v3.json
vulnerability-rating-taxonomy.json

Add bitsquatting

---

CHANGELOG.md
vulnerability-rating-taxonomy.json

**Issue**: Resolves #98 
[`AV:N/AC:H/PR:N/UI:R/S:U/C:N/I:N/A:N`](https://github.com/bugcrowd/vulnerability-rating-taxonomy/blob/master/mappings/cvss_v3.json#L239)
**[Deprecated Node Mapping](https://github.com/bugcrowd/vulnerability-rating-taxonomy/blob/master/deprecated-node-mapping.json)**:
N/A

Add Right-to-Left Override (RTLO)

---

CHANGELOG.md
deprecated-node-mapping.json

Fix invalid id in deprecated node mapping [backport to 1.3]

---

CHANGELOG.md

Changelog updates to release 1.3.1 (tag to come once this is merged)

Cut v1.3.1

---

tests/test_vrt.py
tests/utils.py

@plr0man, thinking about the tests in #112 some more, it seems like a good idea to automatically check all the mapping files in the mappings directory so we don't have to remember to add them to the tests. What do you think about the following? (Note: this is a PR into your branch)

Automatically test all mapping files

---

.github/PULL_REQUEST_TEMPLATE.md
CHANGELOG.md
mappings/cwe.json
mappings/cwe.schema.json
tests/test_vrt.py
tests/utils.py
vulnerability-rating-taxonomy.json

**Issue**: Resolves #99
This is the first iteration of the VRT to CWE mapping. There still a lot of work to be done on the specific CWE<->VRT node mappings, but the logic is ready to review. Cheers!

Add VRT to CWE mapping

---

CHANGELOG.md
mappings/cvss_v3.json
mappings/cwe.json
vulnerability-rating-taxonomy.json

**Issue**: Resolves #110 
[`AV:N/AC:H/PR:H/UI:N/S:U/C:L/I:L/A:N`](https://www.first.org/cvss/calculator/3.0#CVSS:3.0/AV:N/AC:H/PR:H/UI:N/S:U/C:L/I:L/A:N)
**[CWE Mapping](https://github.com/bugcrowd/vulnerability-rating-taxonomy/blob/master/mappings/cwe.json)**:
[CWE-250](https://cwe.mitre.org/data/definitions/250.html)

Add 'Database Management System (DBMS) Misconfiguration' subcategory

---

mappings/remediation_advice.json

Updated:
username_enumeration -- brute_force
insecure_ssl -- lack_of_forward_secrecy

VRT Remediation Updates

---

CHANGELOG.md
mappings/cvss_v3.json
vulnerability-rating-taxonomy.json

**Issue**: Resolves #123 
[AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N](https://www.first.org/cvss/calculator/3.0#CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N)
**[CWE Mapping](https://github.com/bugcrowd/vulnerability-rating-taxonomy/blob/master/mappings/cwe.json)**:
[CWE-79](https://cwe.mitre.org/data/definitions/79.html)

Add CSRF/URL-Based Stored XSS

---

CHANGELOG.md
mappings/cvss_v3.json
mappings/cwe.json
vulnerability-rating-taxonomy.json

**Issue**: Resolves #124
- server_security_misconfiguration.oauth_misconfiguration.account_takeover
[AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H](https://www.first.org/cvss/calculator/3.0#CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H)
**[CWE Mapping](https://github.com/bugcrowd/vulnerability-rating-taxonomy/blob/master/mappings/cwe.json)**:
- server_security_misconfiguration.oauth_misconfiguration [CWE-303](https://cwe.mitre.org/data/definitions/303.html)
- server_security_misconfiguration.oauth_misconfiguration.insecure_redirect_uri [CWE-938](https://cwe.mitre.org/data/definitions/938.html)

Revise OAuth Misconfiguration subcategory

---

CHANGELOG.md
mappings/cvss_v3.json
vulnerability-rating-taxonomy.json

**Issue**: Resolves #131 
`privilege_escalation` (Default Folder Privilege Escalation): [AV:L/AC:H/PR:N/UI:N/S:U/C:L/I:L/A:N](https://www.first.org/cvss/calculator/3.0#CVSS:3.0/AV:L/AC:H/PR:N/UI:N/S:U/C:L/I:L/A:N)
`non_default_folder_privilege_escalation`: [AV:L/AC:H/PR:L/UI:R/S:U/C:L/I:L/A:N](https://www.first.org/cvss/calculator/3.0#CVSS:3.0/AV:L/AC:H/PR:L/UI:R/S:U/C:L/I:L/A:N)
`no_privilege_escalation`: [AV:L/AC:H/PR:H/UI:N/S:U/C:N/I:N/A:N](https://www.first.org/cvss/calculator/3.0#CVSS:3.0/AV:L/AC:H/PR:H/UI:N/S:U/C:N/I:N/A:N)
**[CWE Mapping](https://github.com/bugcrowd/vulnerability-rating-taxonomy/blob/master/mappings/cwe.json)**: N/A (by parent)

Revise 'Binary Planting' variants

---

CHANGELOG.md
deprecated-node-mapping.json
mappings/cvss_v3.json
mappings/cwe.json
vulnerability-rating-taxonomy.json

**Issue**: Resolves #135
`not_operational`: [AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N](https://www.first.org/cvss/calculator/3.0#CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N)
`other_plaintext_protocol_no_secure_alternative`: [AV:A/AC:L/PR:N/UI:R/S:U/C:L/I:L/A:N](https://www.first.org/cvss/calculator/3.0#CVSS:3.0/AV:A/AC:L/PR:N/UI:R/S:U/C:L/I:L/A:N)
`lan_only`: [AV:A/AC:H/PR:N/UI:N/S:U/C:L/I:L/A:N](https://www.first.org/cvss/calculator/3.0#CVSS:3.0/AV:A/AC:H/PR:N/UI:N/S:U/C:L/I:L/A:N)
`http_and_https_available`: [AV:A/AC:L/PR:N/UI:R/S:U/C:L/I:L/A:N](https://www.first.org/cvss/calculator/3.0#CVSS:3.0/AV:A/AC:L/PR:N/UI:R/S:U/C:L/I:L/A:N)
`https_not_available_or_http_by_default`: …

Revise Weak Login Function subcategory

---

.github/PULL_REQUEST_TEMPLATE.md
CHANGELOG.md
mappings/remediation.json
mappings/remediation_advice.json
mappings/remediation_advice.schema.json
tests/utils.py

Adds remediation advice mapping to VRT

Add VRT to Remediation mapping

---

.github/CONTRIBUTING.md
README.md

- Cleans up links so they are all relative
- Adds list of supported mappings
Unfortunately the wiki link doesn't work with only a path 🤷‍♂️

add supported mappings list

---

CHANGELOG.md
mappings/cvss_v3.json
mappings/remediation_advice.json
vulnerability-rating-taxonomy.json

**Issue**: Resolves #137 
[AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:L](https://www.first.org/cvss/calculator/3.0#CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:L)

Remove staging environment distinction from the VRT

---

CHANGELOG.md
vulnerability-rating-taxonomy.json

v1.4 release

---

CHANGELOG.md
mappings/cvss_v3.json
vulnerability-rating-taxonomy.json

**Issue**: Resolves #152 
- `broken_authentication_and_session_management.session_fixation.remote_attack_vector`: [AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:L/A:N](https://www.first.org/cvss/calculator/3.0#CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:L/A:N)
- `broken_authentication_and_session_management.session_fixation.local_attack_vector`: [AV:P/AC:H/PR:L/UI:R/S:U/C:H/I:L/A:N](https://www.first.org/cvss/calculator/3.0#CVSS:3.0/AV:P/AC:H/PR:L/UI:R/S:U/C:H/I:L/A:N)
**[CWE Mapping](https://github.com/bugcrowd/vulnerability-rating-taxonomy/blob/master/mappings/cwe.json)**: no changes
**[Remediation Advice Mapping](https://github.com/bugcrowd/vulnerability-rating-taxonomy/blob/master/mappings/re …

Revise 'Session Fixation' class to be more clear

---

CHANGELOG.md
mappings/cvss_v3.json
mappings/cwe.json
mappings/remediation_advice.json
vulnerability-rating-taxonomy.json

**Issue**: Resolves #153 
**[CVSS v3 Mapping](https://github.com/bugcrowd/vulnerability-rating-taxonomy/blob/master/mappings/cvss_v3.json)**: [AV:A/AC:H/PR:N/UI:N/S:U/C:L/I:L/A:N](https://www.first.org/cvss/calculator/3.0#CVSS:3.0/AV:A/AC:H/PR:N/UI:N/S:U/C:L/I:L/A:N)
**[CWE Mapping](https://github.com/bugcrowd/vulnerability-rating-taxonomy/blob/master/mappings/cwe.json)**: [CWE-319](https://cwe.mitre.org/data/definitions/319.html)
**[Remediation Advice Mapping](https://github.com/bugcrowd/vulnerability-rating-taxonomy/blob/master/mappings/remediation_advice.json)**: _Ensure that session tokens are transmitted over protected channels at all times. If the secure cookie flag is not an option ensure that the application does not support unencrypted communication._ …

Add Cleartext Transmission of Session Token

---

CHANGELOG.md
mappings/cwe.json
mappings/cwe.schema.json

**Issue**: Resolves #161 
**[CWE Mapping](https://github.com/bugcrowd/vulnerability-rating-taxonomy/blob/master/mappings/cwe.json)**: Change default to null

Remove default for CWE mapping

---

CHANGELOG.md
vulnerability-rating-taxonomy.json

Add DNS Query Only SSRF

---

CHANGELOG.md
mappings/cvss_v3.json
mappings/remediation_advice.json
vulnerability-rating-taxonomy.json

**Issue**: Resolves #159 
**[CVSS v3 Mapping](https://github.com/bugcrowd/vulnerability-rating-taxonomy/blob/master/mappings/cvss_v3.json)**:[AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:L](https://www.first.org/cvss/calculator/3.0#CVSS:3.0/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:L)
**[CWE Mapping](https://github.com/bugcrowd/vulnerability-rating-taxonomy/blob/master/mappings/cwe.json)**: Any suggestions?
"To ensure that your origin servers cannot be accessed directly, only accept traffic coming from your Web Application Firewall provider's IP ranges, rather than trusting that your servers remain inaccessible due to their IP's being secret., …

Add WAF Bypass > Direct Server Access

---

CHANGELOG.md
mappings/cvss_v3.json
mappings/cwe.json
mappings/remediation_advice.json
vulnerability-rating-taxonomy.json

**Issue**: Resolves #94 
**[CVSS v3 Mapping](https://github.com/bugcrowd/vulnerability-rating-taxonomy/blob/master/mappings/cvss_v3.json)**:[AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:N](https://www.first.org/cvss/calculator/3.0#CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:N)
**[CWE Mapping](https://github.com/bugcrowd/vulnerability-rating-taxonomy/blob/master/mappings/cwe.json)**:[CWE-304](https://cwe.mitre.org/data/definitions/304.html)
**[Remediation Advice Mapping](https://github.com/bugcrowd/vulnerability-rating-taxonomy/blob/master/mappings/remediation_advice.json)**:Inherited from the parent, same way as Authentication Bypass

Add Second Factor Authentication Bypass

---

mappings/cwe.json
mappings/cwe.schema.json

**Issue**: Resolves #160 
Filing based on @jcran's PR with all updates as discussed there.

Update CWE mapping based on #160

---

CHANGELOG.md
Dockerfile
tests/test_deprecated_mapping.py
tests/utils.py

**Issue:**
Python 2 EOL in 2 years

Made compatible with python 3

---

CHANGELOG.md
mappings/remediation_advice.json
vulnerability-rating-taxonomy.json

**Issue**: Resolves #176 
**[CVSS v3 Mapping](https://github.com/bugcrowd/vulnerability-rating-taxonomy/blob/master/mappings/cvss_v3.json)**: Inherited from parent [AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:N](https://www.first.org/cvss/calculator/3.0#CVSS:3.0/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:N)
**[CWE Mapping](https://github.com/bugcrowd/vulnerability-rating-taxonomy/blob/master/mappings/cwe.json)**: N/A
"As a best practice, consider resolving any SSL certificate errors in order to establish trust and allow secure connections."
https://cheapsslsecurity.com/blog/google-chrome-ssl-certificate-errors-troubleshoot-guide/

Add SSL Certificate Error

---

CHANGELOG.md
deprecated-node-mapping.json
mappings/cvss_v3.json
mappings/cwe.json
mappings/remediation_advice.json
vulnerability-rating-taxonomy.json

**Issue**: Resolves #187 
`server_security_misconfiguration.captcha.missing`: [AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N](https://www.first.org/cvss/calculator/3.0#CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N)
**[CWE Mapping](https://github.com/bugcrowd/vulnerability-rating-taxonomy/blob/master/mappings/cwe.json)**:
Inherited from parent: [CWE-804](https://cwe.mitre.org/data/definitions/804.html)
"As a best practice, consider using CAPTCHAs to prevent automated software from engaging in abusive activities on your site."
**[Deprecated Node …

Add Missing CAPTCHA

---

CHANGELOG.md
mappings/cvss_v3.json
vulnerability-rating-taxonomy.json

**Issue**: Resolves #188 
**[CVSS v3 Mapping](https://github.com/bugcrowd/vulnerability-rating-taxonomy/blob/master/mappings/cvss_v3.json)**: [AV:N/AC:H/PR:N/UI:R/S:U/C:N/I:N/A:N](https://www.first.org/cvss/calculator/3.0#CVSS:3.0/AV:N/AC:H/PR:N/UI:R/S:U/C:N/I:N/A:N)
**[CWE Mapping](https://github.com/bugcrowd/vulnerability-rating-taxonomy/blob/master/mappings/cwe.json)**: Inherited from parent [CWE-352](https://cwe.mitre.org/data/definitions/352.html)
**[Remediation Advice Mapping](https://github.com/bugcrowd/vulnerability-rating-taxonomy/blob/master/mappings/remediation_advice.json)**: Inherited from parent
"1. Consider using a known and secure CSRF synchronizer API and apply the generated CSRF token to every request. If infeasible to apply to every request, generate a CSRF token for …

Add CSRF Token Not Unique Per Request

---

CHANGELOG.md
vulnerability-rating-taxonomy.json

- unvalidated_redirects_and_forwards.open_redirect.flash_based
- cross_site_scripting_xss.flash_based
- server_side_injection.content_spoofing.flash_based_external_authentication_injection
- broken_authentication_and_session_management.session_fixation.remote_attack_vector
- broken_authentication_and_session_management.session_fixation.local_attack_vector
- broken_authentication_and_session_management.cleartext_transmission_of_session_token
- broken_access_control.server_side_request_forgery_ssrf.dns_query_only
- mobile_security_misconfiguration.clipboard_enabled
- mobile_security_misconfiguration.clipboard_enabled.on_sensitive_content
- mobile_security_misconfiguration.clipboard_enabled.on_non_sensitive_content
- server_security_misconfiguration.waf_bypass.direct_server_access
- …

cut v1.5 release

---

CHANGELOG.md
vulnerability-rating-taxonomy.json

broken_access_control.server_side_request_forgery_ssrf.internal_high_impact
broken_access_control.server_side_request_forgery_ssrf.internal_scan_and_or_medium_impact
server_security_misconfiguration.mail_server_misconfiguration.no_spoofing_protection_on_email_domain
server_security_misconfiguration.mail_server_misconfiguration.email_spoofing_to_inbox_due_to_missing_or_misconfigured_dmarc_on_email_domain
server_security_misconfiguration.mail_server_misconfiguration.email_spoofing_to_spam_folder
server_security_misconfiguration.mail_server_misconfiguration.missing_or_misconfigured_spf_and_or_dkim
broken_access_control.server_side_request_forgery_ssrf.internal
server_security_misconfiguration.mail_server_misconfiguration.email_spoofing_on_email_domain …

Update release dates in metadata and changelog for v1.6

---

CHANGELOG.md
deprecated-node-mapping.json
vulnerability-rating-taxonomy.json

**Issue**: Resolves #207 
**[CVSS v3 Mapping](https://github.com/bugcrowd/vulnerability-rating-taxonomy/blob/master/mappings/cvss_v3.json)**: no changes
**[CWE Mapping](https://github.com/bugcrowd/vulnerability-rating-taxonomy/blob/master/mappings/cwe.json)**: no changes
**[Remediation Advice Mapping](https://github.com/bugcrowd/vulnerability-rating-taxonomy/blob/master/mappings/remediation_advice.json)**: no changes
**[Deprecated Node Mapping](https://github.com/bugcrowd/vulnerability-rating-taxonomy/blob/master/deprecated-node-mapping.json)**:
`broken_access_control.username_enumeration.data_leak` will map to `broken_access_control.username_enumeration.non_brute_force`

Revise username enumeration entry names

---

CHANGELOG.md
mappings/remediation_advice.json

**Issue**: Resolves #214 
Credit to @jquinard

Update OWASP reference URLs

---

mappings/cvss_v3/cvss_v3.json
mappings/cwe/cwe.json
mappings/remediation_advice/remediation_advice.json
vulnerability-rating-taxonomy.json

**Issue**: Resolves #202
This PR does not include mappings, which will be added separately. The mapping files included here are to meet basic schema validation requirements.

Add Automotive Security Misconfiguration category (no mappings)

---

.github/PULL_REQUEST_TEMPLATE.md

Checklists are nice for things that are easy to forget
Adds a checklist to the template similar to: https://github.com/bugcrowd/vrt-ruby/blob/master/.github/PULL_REQUEST_TEMPLATE.md

Add checklist to pull request template

---

CHANGELOG.md

We forgot the changelog entries for automotive, this adds them.

Add automotive entries to changelog

---

CHANGELOG.md
vulnerability-rating-taxonomy.json

Release v1.7

---

README.md

Detail the different files and how they fit within the file structure of the repository.

Improve mapping structure documentation

---

CHANGELOG.md
mappings/cvss_v3/cvss_v3.json
mappings/cwe/cwe.json
mappings/remediation_advice/remediation_advice.json
vulnerability-rating-taxonomy.json

Add Indicators of Compromise category

---

CHANGELOG.md
vulnerability-rating-taxonomy.json

Release v1.7.1

---

CHANGELOG.md
mappings/cvss_v3/cvss_v3.json
mappings/cwe/cwe.json
mappings/remediation_advice/remediation_advice.json
vulnerability-rating-taxonomy.json

https://cwe.mitre.org/data/definitions/362.html
https://cwe.mitre.org/data/definitions/366.html
https://cwe.mitre.org/data/definitions/368.html
https://cwe.mitre.org/data/definitions/421.html
"The key to preventing a race condition is to find a way to synchronize or otherwise strictly control the order of operations in potentially vulnerable functions and actions. The best way to do this is through locks. Most programming languages have a built-in locking functionality for data; for example, Python has “threading.Lock”, and Go has “sync.Mutex”. Refer to the documentation for your programming language of choice for more information. If the language has multi-threaded or asynchronous capabilities built-in, it should have some form of locking mechanism available to you." …

Add Race Condition

---

CHANGELOG.md
mappings/cvss_v3/cvss_v3.json
mappings/cwe/cwe.json
mappings/remediation_advice/remediation_advice.json
vulnerability-rating-taxonomy.json

The most robust defense against cache poisoning is to disable caching. This is plainly unrealistic advice for some, but it's likely that some websites that start using a service like Cloudflare for DDoS protection or easy SSL end up vulnerable to cache poisoning simply because caching is enabled by default.
Restricting caching to purely static responses is also effective, provided you're sufficiently wary about what you define as 'static'.
Likewise, avoiding taking input from headers and cookies is an effective way to prevent cache poisoning, but it's hard to know if other layers and frameworks are sneaking in support for extra headers. You might want to audit every page of your application with Param Miner to flush out unkeyed inputs.
Once you've identified unkeyed inputs in your …

Add Cache Poisoning

---

CHANGELOG.md
mappings/cvss_v3/cvss_v3.json
mappings/cwe/cwe.json
mappings/remediation_advice/remediation_advice.json
vulnerability-rating-taxonomy.json

Reverts bugcrowd/vulnerability-rating-taxonomy#240

Revert "Revert "Add Indicators of Compromise category""

---

CHANGELOG.md
vulnerability-rating-taxonomy.json

Update capitalization of Email Spoofing on non-email domain

---

CHANGELOG.md
mappings/cvss_v3/cvss_v3.json
vulnerability-rating-taxonomy.json

- [x ] I have added entries to `CHANGELOG.md` and marked it Added/Changed/Removed

Update Clipboard Enabled

---

.github/CONTRIBUTING.md
.github/workflows/main.yml
tests/requirements.txt

**No mappings no taxonomy change**

Try GitHub actions

---

CHANGELOG.md
deprecated-node-mapping.json
mappings/cvss_v3/cvss_v3.json
mappings/cwe/cwe.json
mappings/remediation_advice/remediation_advice.json
vulnerability-rating-taxonomy.json

`for_publicly_accessible_asset` [AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:L](https://www.first.org/cvss/calculator/3.0#CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:L)
`for_internal_asset` [AV:A/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:L](https://www.first.org/cvss/calculator/3.0#CVSS:3.0/AV:A/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:L)
`pay_per_use_abuse` [AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L](https://www.first.org/cvss/calculator/3.0#CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L)
`intentionally_public_sample_or_invalid` [AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N](https://www.first.org/cvss/calculator/3.0#CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N)
`data_traffic_spam` [AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N](https://www.first.org/cvss/calculator/3.0#CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N)
`non_corporate_user` …

Revise Sensitive Data Exposure > Critically Sensitive Data

---

CHANGELOG.md
mappings/cwe/cwe.json
mappings/remediation_advice/remediation_advice.json
vulnerability-rating-taxonomy.json

Consider eliminating any potential for users bypassing your platform's password policy enforcement. For instance if the password policy is only enforced on the client side, consider adding a corresponding validation on the server side.

Add Password Policy Bypass

---

CHANGELOG.md
deprecated-node-mapping.json
mappings/remediation_advice/remediation_advice.json
vulnerability-rating-taxonomy.json

"As a best practice, consider verifying a method of contact, such as email or phone number when a new account is created or when there is an update to the contact information on record."
`insufficient_security_configurability.lack_of_verification_email` maps to `insufficient_security_configurability.verification_of_contact_method_not_required`

Update Lack of Verifcation Email

---

CHANGELOG.md
deprecated-node-mapping.json
mappings/cvss_v3/cvss_v3.json
vulnerability-rating-taxonomy.json

all 3 deleted variants under broken_authentication_and_session_management.weak_login_function map to broken_authentication_and_session_management.weak_login_function.over_http:
- https_not_available_or_http_by_default
- http_and_https_available
- weak_login_function.lan_only

Revise Weak Login Function Severity Ratings

---

CHANGELOG.md
deprecated-node-mapping.json
mappings/cvss_v3/cvss_v3.json
vulnerability-rating-taxonomy.json

-`server_side_injection.content_spoofing.flash_based_external_authentication_injection` : [AV:N/AC:H/PR:N/UI:R/S:U/C:N/I:N/A:N](https://www.first.org/cvss/calculator/3.0#CVSS:3.0/AV:N/AC:H/PR:N/UI:R/S:U/C:N/I:N/A:N)
-`cross_site_scripting_xss.flash_based` : [AV:N/AC:H/PR:N/UI:R/S:C/C:N/I:N/A:N](https://www.first.org/cvss/calculator/3.0#CVSS:3.0/AV:N/AC:H/PR:N/UI:R/S:C/C:N/I:N/A:N)
-`cross_site_request_forgery_csrf.flash_based` : [AV:N/AC:H/PR:N/UI:R/S:U/C:N/I:N/A:N](https://www.first.org/cvss/calculator/3.0#CVSS:3.0/AV:N/AC:H/PR:N/UI:R/S:U/C:N/I:N/A:N)
-`using_components_with_known_vulnerabilities.rosetta_flash` : [AV:N/AC:H/PR:N/UI:R/S:U/C:N/I:N/A:N](https://www.first.org/cvss/calculator/3.0#CVSS:3.0/AV:N/AC:H/PR:N/UI:R/S:U/C:N/I:N/A:N)
- …

Downgrade Flash-based entries

---

mappings/cvss_v3/cvss_v3.json
vulnerability-rating-taxonomy.json

Adding LDAP Injection as a new VRT entry.

LDAP Injection

---

third-party-mappings/remediation_training/secure-code-warrior-links.json

Removed duplicate line 138,139 in: https://github.com/bugcrowd/vulnerability-rating-taxonomy/blob/master/third-party-mappings/remediation_training/secure-code-warrior-links.json

Fixing duplicate error

---

third-party-mappings/remediation_training/secure-code-warrior-links.json

SCW update for AI security for v1.12 release

---

CHANGELOG.md
vulnerability-rating-taxonomy.json

Adding CHANGELOG and release date

Adding Changelog and Release Date

---

CHANGELOG.md
vulnerability-rating-taxonomy.json

Updates 'Password Reset Token'  subcategory to variant

adding changelog and release date for v1.14.1 release
